services:
  # transpicere-dev:
  #   build: .
  #   depends_on:
  #     - mysql
  #     - postgres
  myql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password    
  postgres:
    image: "postgres:latest"
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_transpicere
  webapp:
    build: 
      dockerfile: ./Dockerfile_webapp
      context: .
    restart: always
    volumes:
      - ./transpicere:/code/transpicere
      - ./web:/code/web
    ports:
      - 5000:5000
    depends_on:
      - postgres
    command: sh -c './wait-for.sh postgres:5432 -- python -m web.app'

  test:
    build: 
      dockerfile: ./Dockerfile_test
      context: .
    volumes:
      - ./transpicere:/code/transpicere
      - ./test:/code/test
    depends_on:
      - postgres
    command: sh -c './wait-for.sh postgres:5432 -- python -m pytest --cov=transpicere --cov-report term-missing ./test'
