FROM python:3.9
RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat \
    unixodbc-dev  unixodbc  libsqliteodbc sqlite3 odbc-postgresql
WORKDIR /code
COPY requirements.txt .
RUN pip3 install --compile -r requirements.txt 

COPY requirements-dev.txt .
RUN pip3 install --compile -r requirements-dev.txt

# copy only the dependencies installation from the 1st stage image

ENV PATH=/root/.local:$PATH

COPY transpicere ./transpicere
COPY test ./test
COPY wait-for.sh .
# COPY test/data /root

# postgres odbc driver: \usr\lib\x86_64-linux-gnu\odbc\psqlodbcw.so

RUN sqlite3 /root/transpicere.db
RUN sqlite3 /root/transpicere.db .show
# Build stage test - run tests
# CMD ["/bin/sh"]
# CMD ["ls","-al", "/root/"]
# CMD ["sqlite3", "/root/transpicere.db", ".show"]
CMD ["python", "-m", "pytest", "./test" ]
# CMD ["/root/odbcconf.sh"]
