name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install -r ./requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./transpicere --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./test      --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: type checking with mypy
      run: |
        python -m mypy --config-file mypy.ini
    - name: Test with pytest
      run: |
        docker-compose run test
